openapi: 3.1.0
info:
  version: 0.0.1
  title: カルタグラフ
  description: カルタグラフ用API

  contact:
    name: hibohiboo
    url: https://twitter.com/hibohiboo

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.example.com/v1/api
    description: バージョンとapiであることを表す部分までは共通

paths:
  /tags:
    $ref: paths/tags.yml
  /scenario/{scenarioId}/tags:
    $ref: paths/scenario.yml
  /scenario/list:
    $ref: paths/scenario-list.yml


components:
  securitySchemes:
    ApiKeyAuth:
      $ref: components/schemas/apiKey.yml

