# You must change these to your own details.
[package]
authors = ["You <you@example.com>"]
categories = ["wasm"]
description = "My super awesome Rust, WebAssembly, and Webpack project!"
edition = "2021"
license = "MIT"
name = "test_wasm"
readme = "README.md"
repository = ""
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
path = "rust/lib.rs"

[profile.release]
lto = true

[features]

[dependencies]
gloo-utils = {version = "0.2.0", features = ["serde"]}
js-sys = "0.3.69"
serde = {version = "1.0.203", features = ["derive"]}
wasm-bindgen = "0.2.92"

# The `web-sys` crate allows you to interact with the various browser APIs,
# like the DOM.
[dependencies.web-sys]
features = ["console"]
version = "0.3.69"

# These crates are used for running unit tests.
[dev-dependencies]
js-sys = "0.3.69"
wasm-bindgen-test = "0.3.42"
